name: base
variables:
  - name: url
    value: 'https://serverest.dev'
    type: text
    enabled: true
    secret: false
  - name: idUsuarioDuplicado
    value: ''
    type: text
    enabled: true
    secret: false
  - name: emailDuplicado
    value: duplicado@qa.com.br
    type: text
    enabled: true
    secret: false
  - name: nomeAtualizado
    value: Fulano Atualizado
    type: text
    enabled: true
    secret: false
  - name: idSegundoUsuario
    value: ''
    type: text
    enabled: true
    secret: false
  - name: token
    value: ''
    type: text
    enabled: true
    secret: false
  - name: idUserAdmin
    value: ''
    type: text
    enabled: true
    secret: false
  - name: idProdutoDuplicado
    value: ''
    type: text
    enabled: true
    secret: false
  - name: nomeProdutoDuplicado
    value: Mouse verde
    type: text
    enabled: true
    secret: false
  - name: idSegundoProduto
    value: ''
    type: text
    enabled: true
    secret: false
  - name: carrinhoCriado
    value: ''
    type: text
    enabled: true
    secret: false
info:
  type: bruno-environment
  exportedAt: '2026-03-25T02:07:05.587Z'
  exportedUsing: Bruno/v3.2.0
